### ISSUE TITLE
在Vite4.1.1版本新建项目里接入Veaury插件报错

### ISSUE THREAD

**Issue by donglinkai** [devilwjp/veaury#59]
Vite v4.1.1（目前默认最新的版本）项目新建模板是vue-ts
组件内的代码没有任何改动，就只有helloworld.vue 和App.vue两个组件
下面是vite配置信息和错误信息，如果需要其他的信息可@我
幸苦大大排查一下了

vite.config.ts文件
````typescript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import veauryVitePlugins from 'veaury/vite'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(),
    veauryVitePlugins({ type: 'vue'})],
})

````

控制台错误信息
````
 VITE v4.1.1  ready in 551 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
At least one <template> or <script> is required in a single file component.
08:57:14 [vite] Internal server error: At least one <template> or <script> is required in a single file component.
  Plugin: vite:vue
  File: C:/Users/dongl/Desktop/projects/vite-project/src/App.vue
      at Object.parse$4 [as parse] (C:\Users\dongl\Desktop\projects\vite-project\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:5269:21)
      at createDescriptor (C:\Users\dongl\Desktop\projects\vite-project\node_modules\@vitejs\plugin-vue\dist\index.cjs:68:43)
      at transformMain (C:\Users\dongl\Desktop\projects\vite-project\node_modules\@vitejs\plugin-vue\dist\index.cjs:2210:34)
      at TransformContext.transform (C:\Users\dongl\Desktop\projects\vite-project\node_modules\@vitejs\plugin-vue\dist\index.cjs:2702:16)
      at Object.transform (file:///C:/Users/dongl/Desktop/projects/vite-project/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41660:44)
      at async loadAndTransform (file:///C:/Users/dongl/Desktop/projects/vite-project/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39466:29)

````

package.json
````json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vitejs/plugin-react": "^3.1.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "veaury": "^2.3.12",
    "vue": "^3.2.45"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.1.0",
    "vue-tsc": "^1.0.24"
  }
}

````

**Comment by devilwjp** [comment]
@donglinkai 使用veauryVitePlugin就不需要再使用`vue()`了

**Comment by bitbitDown** [comment]
> @donglinkai 使用veauryVitePlugin就不需要再使用`vue()`了，注释掉这句
谢谢大佬，我调了一个小时，终于好了
