### ISSUE TITLE
无法在Vue项目中使用React

### ISSUE THREAD

**Issue by moshuying** [devilwjp/veaury#94]
您好，我的项目使用了 vue3和react 18。尝试在项目中使用react three fiber却一直报错
```
react-dom.development.js:14887  Uncaught Error: Objects are not valid as a React child (found: object with keys {__v_isVNode, __v_skip, type, props, key, ref, scopeId, slotScopeIds, children, component, suspense, ssContent, ssFallback, dirs, transition, el, anchor, target, targetAnchor, staticCount, shapeFlag, patchFlag, dynamicProps, dynamicChildren, appContext, ctx}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at mountIndeterminateComponent (react-dom.development.js:20157:5)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
   ```
   
![image](https://github.com/devilwjp/veaury/assets/37231523/4ed09336-09d9-4ecd-bb0a-4416c68a10d5)
![image](https://github.com/devilwjp/veaury/assets/37231523/0f8c5123-75c4-492f-a1bd-4dde359277ef)
![image](https://github.com/devilwjp/veaury/assets/37231523/15566908-aa49-45a0-ab97-ff40518ce49c)

**Comment by moshuying** [comment]
tsx 组件在编译时不一定能看到报错，先写JSX组件处理掉报错后即可，我这边的报错是找不到deri包，尽管再package.json中有，还是需要再安装一遍（NPM背锅！）

**Comment by KingGanZeng** [comment]
我也遇到了这个报错，原因是因为我的tsconfig中extends了@vue/tsconfig/tsconfig.json，其中定义了jsx的编译规则：
<img width="340" alt="image" src="https://github.com/devilwjp/veaury/assets/22743840/c0e7b2d7-733e-4f71-a91c-6e68de16d619">
jsxImportSource，是用于指定从哪个模块导入 JSX 工厂函数
在这个配置里，react jsx会转入vue的编译规则里，解决办法就是移除这个extends，手动添加需要的规则，最简单的版本是这样的：
```json
{
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue",
    "vite.config.*"
  ],
  "compilerOptions": {
    "composite": true,
    "types": [
      "node"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  }
}
```
