### ISSUE TITLE
官方的仓库跑不起来

### ISSUE THREAD

**Issue by tanqiyou1990** [devilwjp/veaury#98]
不管是在根目录下运行还是在dev-project-vue下 启动报错如下：
 ERROR  Failed to compile with 1 error                                                                                                                18:10:12

 error  in ./src/pages/vueMissReact/index.vue?vue&type=script&setup=true&lang=js

Syntax Error: TypeError: Cannot read properties of null (reading 'content')

 @ ./src/pages/vueMissReact/index.vue?vue&type=script&setup=true&lang=js 1:0-299 1:0-299 1:300-588 1:300-588
 @ ./src/pages/vueMissReact/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (webpack)-dev-server/client?http://192.168.0.141:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by devilwjp** [comment]
@tanqiyou1990 这个问题是因为你安装的vue-cli版本不支持jsx，请先确保你本地的vue-cli支持jsx配置

**Comment by ChenChunChang** [comment]
@tanqiyou1990 #98请问这个问题解决了吗，能告诉下怎么处理吗

**Comment by devilwjp** [comment]
@ChenChunChang 这个问题应该是你本地vue-cli版本不支持jsx的问题

**Comment by devilwjp** [comment]
@ChenChunChang 你可以先自己用vue-cli创建一个vue项目，然后编写vue的jsx看看是否报同样的错误

**Comment by ChenChunChang** [comment]
@devilwjp 好的多谢，我来试试

**Comment by ChenChunChang** [comment]
> vue的jsx
本地是@vue/cli 5.0.8，我切换成vue --version  3.12.1后运行本仓库依旧报错
@vue/cli 5.0.8报错内容如下
`vue-cli-service serve
 INFO  Starting development server...
0% compiling ERROR  TypeError: Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@5.91.0\node_modules\webpack\lib\DefinePlugin.js:354:38
    at SyncHook.eval [as call] (eval at create (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:25:1)
    at SyncHook.lazyCompileHook (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Compiler.js:631:26)
    at E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Compiler.js:662:28)
    at E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Watching.js:41:32)
    at E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Compiler.js:529:11)
    at new Watching (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Watching.js:30:17)
    at Compiler.watch (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack@4.47.0\node_modules\webpack\lib\Compiler.js:244:10)
    at wdm (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack-dev-middleware@3.7.3_webpack@4.47.0\node_modules\webpack-dev-middleware\index.js:41:33)
    at Server.setupDevMiddleware (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack-dev-server@3.11.3_webpack@4.47.0\node_modules\webpack-dev-server\lib\Server.js:207:23)
    at new Server (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\webpack-dev-server@3.11.3_webpack@4.47.0\node_modules\webpack-dev-server\lib\Server.js:118:10)
    at serve (E:\Mineme\TEST\github\veaury\dev-project-vue3\node_modules\.pnpm\@vue+cli-service@4.5.19_@vue+compiler-sfc@3.4.21_react-dom@18.2.0_react@18.2.0_vue@3.4.21\node_modules\@vue\cli-service\lib\commands\serve.js:172:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

使用vue --version  3.12.1时报错如下：
` ERROR  Failed to compile with 1 error                                                                          15:53:21

 error  in ./src/pages/vueMissReact/index.vue?vue&type=script&setup=true&lang=js

Syntax Error: TypeError: Cannot read properties of null (reading 'content')


 @ ./src/pages/vueMissReact/index.vue?vue&type=script&setup=true&lang=js 1:0-299 1:0-299 1:300-588 1:300-588
 @ ./src/pages/vueMissReact/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (webpack)-dev-server/client?http://192.168.2.8:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
`
本地根据vue create project创建项目使用jsx是正常的
HelloWorld.vue:
`<script lang="jsx">
export default {
  render() {
    return (
      <div>
        <h1>Hello, JSX in Vue 3!</h1>
      </div>
    );
  },
};
</script>`
![image](https://github.com/devilwjp/veaury/assets/25130211/3e896863-0ef7-42dd-a65e-5e1f3edfd92c)


@devilwjp 想问下您的vuecli版本是多少，可以帮您本地可以正常运行的项目提供一个demo让我研究学习下吗

**Comment by devilwjp** [comment]
@ChenChunChang 你看下你的vue是什么版本

**Comment by devilwjp** [comment]
@ChenChunChang 你的问题我复现了，把vue降级到3.2.x版本就好了，原因我排查一下

**Comment by ChenChunChang** [comment]
> @ChenChunChang 你看下你的vue是什么版本

自己本地搭建的vue是^3.2.13

本仓库项目使用的vue是3.0，报错如第二个报错，
`ERROR Failed to compile with 1 error 15:53:21`
当我把它升级到最新，报错如第一个报错 
`vue-cli-service serve  INFO  Starting development`

**Comment by ChenChunChang** [comment]
> @ChenChunChang 你的问题我复现了，把vue降级到3.2.x版本就好了，原因我排查一下

好的多谢，我试试

**Comment by devilwjp** [comment]
@ChenChunChang 问题原因已经找到，vue3.3之后的版本，对于.vue文件中使用jsx有严格的声明要求，需要强制设置<script lang="jsx">

在测试项目中src/pages/pureReactInVue/index.vue和/src/pages/vueMissReact/index.vue没有声明lang="jsx"

**Comment by ChenChunChang** [comment]
> @ChenChunChang 问题原因已经找到，vue3.3之后的版本，对于.vue文件中使用jsx有严格的声明要求，需要强制设置<script lang="jsx">
> 
> 在测试项目中src/pages/pureReactInVue/index.vue和/src/pages/vueMissReact/index.vue没有声明lang="jsx"

好的，解决了，非常感谢
